### ISSUE TITLE
Recursion depth reached for `repr(_context)` containing a copy of itself

### ISSUE THREAD

**Issue by aaaaalbert** [SeattleTestbed/repy_v2#97] opened 2015-04-24 15:14 UTC
If `_context` is made to contain a `.copy()` of itself, then the `str` and `repr` functions fail on it with a recursion error.

Try the code snippet below:

```
str(_context)
log("This worked.\n")

c = _context
log("c currently is just a reference to _context, all OK.\n")
if c is _context:
  log("c is _context\n")   # This gets printed
else:
  log("c is not _context\n")

c = _context.copy()
log("Creating the copy as such is not the problem.\n")
if c is _context:
  log("Now, c is _context\n")
else:
  log("Now, c is not _context\n")   # This gets printed

# But creating a str/repr of _context containing a copy of itself is a problem:
str(_context)
log("Won't reach this :-(\n")
```

`_context` contains references to everything in the Repy namespace, including variables that are defined during runtime, and a reference to itself too:

```
_context = {
  "getmyip": <function ...>,
  "sleep": <function ...>,
  # ...and the rest of the API.
  "_context": _context
}
```

When a variable is added, say `foo = 123`,

```
_context = {
  "getmyip": <function ...>,
  "sleep": <function ...>,
  # ...and the rest of the API.
  "_context": _context,
  "foo": 123
}
```

Also, adding a variable referring to `_context` itself (not a copy of it) works just fine: `c = _context`

```
_context = {
  "getmyip": <function ...>,
  "sleep": <function ...>,
  # ...and the rest of the API.
  "_context": _context,
  "c": _context
}
```

I didn't succeed constructing a similarly failing situation with custom dicts instead of `_context` yet.

See SeattleTestbed/attic#918 where the `repr` method for dicts was patched to allow recursive dicts to be printed.

**Comment by aaaaalbert** [comment] 2015-04-24 16:03
Okay, I think I understand the problem better now.

`c = _context.copy()` makes it so that `c["_context"]` still refers back to the original `_context`. If we change it to refer to the copy just created, things work out correctly:

```
c = _context.copy()
c["_context"] = c

str(_context)
str(c)
log("All fine!\n")
```

This issue thus describes the problem that is mentioned in `safe.py`'s comments (essentially), see the `__repr__` method here: https://github.com/SeattleTestbed/repy_v2/blob/master/safe.py#L720-L731

We should still fix this, however.

**Comment by citester2** [comment] 2016-04-27 21:12
Let me re-phrase the issue:
`c = _context.copy()` creates a new `SafeDict` object where `c.__under__` is a shallow copy of `_context.__under__` (the actual `dict` object):

```
c.__under__ = {
  "_context": _context           # reference to original _context SafeDict object
  "getmyip": <function ...>,     # same reference as _context.__under__["getmyip"]
  "sleep": <function ...>,	 	 # same reference as _context.__under__["sleep"]  
  # ...rest of visibible (safe) references as in _context.__under__
  # ...rest of hidden references as in _context.__under__
}
```
When calling, in `__repr__` method of `SafeDict` a new `dict` object is created which looks like this.

```
newdict = {
  "_context": _context           # still a reference to the original _context
  "getmyip": <function ...>,     # same reference as _context.__under__["getmyip"]
  "sleep": <function ...>,	 	 # same reference as _context.__under__["sleep"]  
  # ...rest of visibible (safe) references as in _context.__under__
}
```

`newdict` is then passed on to Python's built-in `__repr__`, which in turn calls `__repr__` for every item. Most of those are references to `wrapped_function` objects, which return their representation. So far, so good, this is no problem. It get's interesting again when we stumble upon `_context`. This is still the original `SafeDict` object. Therefor we again call our custom `__repr__` method in `SafeDict`, where we copy references from our original `_context.__under__` to a `newdict`. But now when we reach `_context`, which is the contained reference to the `SafeDict` object, this [condition](https://github.com/SeattleTestbed/repy_v2/blob/master/safe.py#L727-L728) should match, which cuts the chain of references to `SafeDict` objects and should let Python's built-in recursion prevention do the rest. But it does not. Instead we call our custom `__repr__` in `SafeDict` again and again.

A temporary fix could be to modify the `copy` method of `SafeDict` to immediately reference the object that will be returned instead of keeping a reference to the object we copy, like so (e.g. [here](https://github.com/SeattleTestbed/repy_v2/blob/master/safe.py#L738)):

```
for key, value in self.__under__.iteritems():
  if value is self:
    copy_inst[key] = copy_inst    # instead of copy_inst[key] = self
 ```

The problem is that one would expect at least one recursion from such a copied dict, before Python's built-in recursion prevention kicks in. Then again, one would also expect that `__repr__` does not throw an exception in this case.

**Comment by lukpueh** [comment] 2016-04-27 21:15
Let me re-phrase the issue:
`c = _context.copy()` creates a new `SafeDict` object where `c.__under__` is a shallow copy of `_context.__under__` (the actual `dict` object):

```
c.__under__ = {
  "_context": _context           # reference to original _context SafeDict object
  "getmyip": <function ...>,     # same reference as _context.__under__["getmyip"]
  "sleep": <function ...>,	 	 # same reference as _context.__under__["sleep"]  
  # ...rest of visibible (safe) references as in _context.__under__
  # ...rest of hidden references as in _context.__under__
}
```
When calling, in `__repr__` method of `SafeDict` a new `dict` object is created which looks like this.

```
newdict = {
  "_context": _context           # still a reference to the original _context
  "getmyip": <function ...>,     # same reference as _context.__under__["getmyip"]
  "sleep": <function ...>,	 	 # same reference as _context.__under__["sleep"]  
  # ...rest of visibible (safe) references as in _context.__under__
}
```

`newdict` is then passed on to Python's built-in `__repr__`, which in turn calls `__repr__` for every item. Most of those are references to `wrapped_function` objects, which return their representation. So far, so good, this is no problem. It get's interesting again when we stumble upon `_context`. This is still the original `SafeDict` object. Therefor we again call our custom `__repr__` method in `SafeDict`, where we copy references from our original `_context.__under__` to a `newdict`. But now when we reach `_context`, which is the contained reference to the `SafeDict` object, this [condition](https://github.com/SeattleTestbed/repy_v2/blob/master/safe.py#L727-L728) should match, which cuts the chain of references to `SafeDict` objects and should let Python's built-in recursion prevention do the rest. But it does not. Instead we call our custom `__repr__` in `SafeDict` again and again.

A temporary fix could be to modify the `copy` method of `SafeDict` to immediately reference the object that will be returned instead of keeping a reference to the object we copy, like so (e.g. [here](https://github.com/SeattleTestbed/repy_v2/blob/master/safe.py#L738)):

```
for key, value in self.__under__.iteritems():
  if value is self:
    copy_inst[key] = copy_inst    # instead of copy_inst[key] = self
 ```

The problem is that one would expect at least one recursion from such a copied dict, before Python's built-in recursion prevention kicks in. Then again, one would also expect that `__repr__` does not throw an exception in this case.

**Comment by lukpueh** [comment] 2017-08-28 16:39
Fixed with https://github.com/SeattleTestbed/repy_v2/issues/97.

**Closed by lukpueh** 2017-08-28 16:39 UTC
